org: shilomagen
app: transcribing-amnon
service: transcribing-amnon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    GCLOUD_PROJECT_ID: ${param:GCLOUD_PROJECT_ID}
    GCLOUD_CLIENT_EMAIL: ${param:GCLOUD_CLIENT_EMAIL}
    GCLOUD_PRIVATE_KEY: ${param:GCLOUD_PRIVATE_KEY}
    CLOUD_API_ACCESS_TOKEN: ${param:CLOUD_API_ACCESS_TOKEN}
    WEBHOOK_VERIFY_TOKEN: ${param:WEBHOOK_VERIFY_TOKEN}

functions:
  handleMessage:
    handler: src/handlers/cloud-api-handler.cloudApiHandler
    events:
      - httpApi:
          path: /incoming-message
          method: '*'

plugins:
  - serverless-plugin-typescript
