org: shilomagen
app: transcribing-amnon
service: transcribing-amnon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    GCLOUD_PROJECT_ID: ${param:GCLOUD_PROJECT_ID}
    GCLOUD_CLIENT_EMAIL: ${param:GCLOUD_CLIENT_EMAIL}
    GCLOUD_PRIVATE_KEY: ${param:GCLOUD_PRIVATE_KEY}
    CLOUD_API_ACCESS_TOKEN: ${param:CLOUD_API_ACCESS_TOKEN}
    WEBHOOK_VERIFY_TOKEN: ${param:WEBHOOK_VERIFY_TOKEN}

constructs:
  nofiticationsQueue:
    type: queue
    worker:
      handler: src/handlers/notification-handler.handle
      timeout: 10
      memorySize: 128
  transcriptionRequest:
    type: queue
    worker:
      handler: src/handlers/transcription-request-handler.handle
      timeout: 100
      memorySize: 512
      environment:
        NOTIFICATIONS_QUEUE_URL: ${construct:nofiticationsQueue.queueUrl}

functions:
  handleMessage:
    handler: src/handlers/cloud-api-handler.cloudApiHandler
    memorySize: 128
    environment:
      TRANSCRIPTION_REQUEST_QUEUE_URL: ${construct:transcriptionRequest.queueUrl}
    events:
      - httpApi:
          path: /incoming-message
          method: 'POST'

plugins:
  - serverless-plugin-typescript
  - serverless-lift
