service: transcribing-amnon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handleMessage:
    handler: src/handlers/incoming-message.handle
    events:
      - httpApi:
          path: /incoming-message
          method: post

plugins:
  - serverless-plugin-typescript
