org: shilomagen
app: transcribing-amnon
service: transcribing-amnon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    GCLOUD_PROJECT_ID: ${param:GCLOUD_PROJECT_ID}
    GCLOUD_CLIENT_EMAIL: ${param:GCLOUD_CLIENT_EMAIL}
    GCLOUD_PRIVATE_KEY: ${param:GCLOUD_PRIVATE_KEY}
    CLOUD_API_ACCESS_TOKEN: ${param:CLOUD_API_ACCESS_TOKEN}
    WEBHOOK_VERIFY_TOKEN: ${param:WEBHOOK_VERIFY_TOKEN}

constructs:
  transcriptionRequest:
    type: queue
    worker:
      handler: src/handlers/transcription-request-handler.handle

functions:
  handleMessage:
    handler: src/handlers/cloud-api-handler.cloudApiHandler
    memorySize: 128
    environment:
      TRANSCRIPTION_REQUEST_QUEUE_URL: ${construct:transcriptionRequest.queueUrl}
    events:
      - httpApi:
          path: /incoming-message
          method: 'POST'
  handleTranscriptionRequest:
    handler: src/handlers/transcription-request-handler.handle
    timeout: 100
    memorySize: 512


plugins:
  - serverless-plugin-typescript
  - serverless-lift
