org: shilomagen
app: transcribing-amnon
service: transcribing-amnon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handleMessage:
    handler: src/handlers/cloud-api-handler.handle
    events:
      - httpApi:
          path: /incoming-message
          method: post

plugins:
  - serverless-plugin-typescript
